### PR TITLE
Add select2 site-search option (and other filters)

### PR DESCRIPTION
**Pull request by jtsternberg**
Related #6

### CODE REVIEW

**Comment by pierre-dargham** [comment]
Hi there,

I finally started working on your PR.

I've pushed all of your commits [on a new branch](https://github.com/pierre-dargham/multisite-clone-duplicator/commits/select2) except for the Coding Standard issues, because I was fixing this myself at the same time.

**For now, I have made a few changes, particularly those two :**

- https://github.com/pierre-dargham/multisite-clone-duplicator/commit/08d74417ff5560ebccfe08908d76b3735ae83f32 : I wanted the select2 select-box to print the ID of the sites (it could be very useful, because in some context, sites are referenced mainly by their IDs)

- https://github.com/pierre-dargham/multisite-clone-duplicator/commit/a54f5025dc9346d1212e66323499b5a1535db2fb : localization of select2 was not activated, it was always in english, even if WP locale was set to something else.

**What I want to do in the future (before release 1.4.0 on wordpress.org) :** (If you work of any of those things, let me know it :) )

- Enable select2 by default, totally remove the old way of selecting sites

- Complete wordpress .po / .mo translations files with the few strings you added

- Maybe, I want to search sites not only by slug (path / domain) but also by ID and title. What do you think of it ?

- Work on the option "Allow duplication of following sites only ". I think I want to have this : 
```
[ ] Allow duplication of all sites of the network

[ ] Allow duplication of following sites only :
--> [ site1, site2, site3 ... ] + select2-box to add a site here

[ ] Allow duplication of all sites of the network, except : 
--> [ site1, site2, site3 ... ] + select2-box to add a site here
```

And I have a question for you :
- Do you think printing by default the 20 first sites of the network in the select2 box would be useful ? It could avoid typing some text when networks are small. 90% of my users are on very small networks and this could be more user-friendly to them.

Thank you for your commits, it is very good work ! I hope we'll continue working together.

Best regards,

Pierre

**Comment by jtsternberg** [comment]
Hey Pierre. We'll likely be looking to use this plugin again on another project, so wanted to check in here to see how things have progressed. How is it going? To respond to some of your questions:

> Maybe, I want to search sites not only by slug (path / domain) but also by ID and title. What do you think of it ?

Yep agree.

> Do you think printing by default the 20 first sites of the network in the select2 box would be useful ? It could avoid typing some text when networks are small. 90% of my users are on very small networks and this could be more user-friendly to them.

Yes, that definitely seems prudent to me.

**Comment by pierre-dargham** [comment]
Hi Justin !

We're a few months late, because some big wp projects for clients took all our time since november.

I'm just back on the multisite-clone-duplicator project and will try to go forward next week.

What I want to do is :

1. Push on github our last developments, including select2 PR, a lot of cleaning / refactoring, and some improvement of the main DB search-replace function (the previous version was not 100% exhaustive : we detected some limit cases with serialized data)

2. Clean the git tree, branches and tags (it's a little messy right now, my fault)

3. Run a lot of tests, fix all bugs, and push v2.0 to wordpress.org before the end of march.

We also have to think about wp-cli community packages and updating the few translations we have, to match v2.0 changes.

I will come back to you after step 2. (it should be next week) so we can talk about the latest development version, clean, here on github.

Thanks for using and improving the plugin !

Bests regards,

Pierre

**Comment by pierre-dargham** [comment]
Hello @jtsternberg @mmcachran :

After 1 year, we finally get back on the plugin :

- We have reset the branches master and develop on github to match wordpress.org state, and we work now with a cleaner git workflow like :

N feature branches -> N pull request on develop -> 1 pull request on master -> 1 tag -> 1 release on wordpress.org

- We published a release 1.3.3 on wordpress.org only for 4.7 compatibility issue

- We are finishing (just need more tests and update readme) release 1.4.0 https://github.com/pierre-dargham/multisite-clone-duplicator/milestone/1 : it will finally provide your select2 feature on the official wordpress.org version of the plugin. If we see no regression, we will publish it this week, or next week.

Feel free to test the develop branch, open issues or pull requests, or to send comments.

Our roadmap for 1.5.0 and 2.x versions will be more or less :
- Fix coding standards
- Better plugin structure and code refactoring
- wp-cli improvements
- search-replace algorithm improvements

Bests regards,

Pierre

**Pull request closed without merging**
